// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP5JaCQY9UflXAJjpbdnojXckOnnWN-uI',
    appId: '1:584699019125:web:b783766a159054dfd19d3c',
    messagingSenderId: '584699019125',
    projectId: 'expense-tracker-5a2e6',
    authDomain: 'expense-tracker-5a2e6.firebaseapp.com',
    storageBucket: 'expense-tracker-5a2e6.firebasestorage.app',
    measurementId: 'G-H31PJM2XPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr96jVbCoEX80gOM0eC-lfaoiswzOdbK0',
    appId: '1:584699019125:android:ce5d08c8e0c36032d19d3c',
    messagingSenderId: '584699019125',
    projectId: 'expense-tracker-5a2e6',
    storageBucket: 'expense-tracker-5a2e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWwv8YSRbkCmj5i4uRl4iwGnj-K7MyxqA',
    appId: '1:584699019125:ios:1be1dfcf2cb12564d19d3c',
    messagingSenderId: '584699019125',
    projectId: 'expense-tracker-5a2e6',
    storageBucket: 'expense-tracker-5a2e6.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWwv8YSRbkCmj5i4uRl4iwGnj-K7MyxqA',
    appId: '1:584699019125:ios:1be1dfcf2cb12564d19d3c',
    messagingSenderId: '584699019125',
    projectId: 'expense-tracker-5a2e6',
    storageBucket: 'expense-tracker-5a2e6.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP5JaCQY9UflXAJjpbdnojXckOnnWN-uI',
    appId: '1:584699019125:web:edf424429cbdd6fdd19d3c',
    messagingSenderId: '584699019125',
    projectId: 'expense-tracker-5a2e6',
    authDomain: 'expense-tracker-5a2e6.firebaseapp.com',
    storageBucket: 'expense-tracker-5a2e6.firebasestorage.app',
    measurementId: 'G-45FMNMPE8R',
  );
}
